int run(int hd);
void read();
int run2(int hd);
int run3(int hd);
int run4(int hd);
int run5(int hd);
int run6(int hd);
int run7(int hd);
int run8(int hd);
int run9(int hd);
int ab(int hd);
int ab2(int hd);
int ab3(int hd);
int ab4(int hd);
double dtanh(double x);
double sigmoid(double x);
double dsigmoid(double x);
double relu(double x);
double drelu(double x);
void readreg();
double crossentrophy(double yhat,double y);
